server:
  port: 11090

spring:
  data:
    mongodb:
      uri: ${USER_MONGODB_URI}

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
