server:
  port: 8080

jwt:
  secret_key: ${JWT_SECRET_KEY}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

purpost:
  origin: http://localhost:4200

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
